---
vms_info:
  - hw_name: "Bootstrap-Romany"
    ip: "192.168.1.124"
    hostname: "bootstrap"
  - hw_name: "Worker1-Romany"
    ip: "192.168.1.115"
    hostname: "worker1"
  - hw_name: "Master1-Romany"
    ip: "192.168.1.116"
    hostname: "master1"  


OCP_BASE_DOMAIN: example.com
OCP_COMPUTE_REPLICAS: 3
OCP_CONTROL_REPLICAS: 3
OCP_CLUSTER_NAME: my-cluster
OCP_INSTALL_DIR: "/root/ocp-install"
OCP_PULL_SECRET: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNzE3MDM5ZjlmMWU5NGE4ZWI5OGVjNDM1MmRiNDI2MzA6Q0lCRDhSMTZFWk5GWDBRQ0tPUFVUSkI0OVdBRFlVVzdKR01VNzIwQ01UT0tXVTdCRDU0OEMyRkdVUU5PTERYSw==","email":"romanyrafaatt@gmail.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNzE3MDM5ZjlmMWU5NGE4ZWI5OGVjNDM1MmRiNDI2MzA6Q0lCRDhSMTZFWk5GWDBRQ0tPUFVUSkI0OVdBRFlVVzdKR01VNzIwQ01UT0tXVTdCRDU0OEMyRkdVUU5PTERYSw==","email":"romanyrafaatt@gmail.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTZmY2E5MDIyLTVjZTAtNDc1My1iNWQ4LTNhNTJjYWMwZTIxNjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTRZekF5TmpWaVlXTXlNR1UwTW1SaE9USXpOakUxWW1VNE9HVm1Zemt6WkNKOS5SbENlZkVCWnpCdjZuSGtJYWpqd3ZYVEMyVTdVXzVEQVh4d1FRT0Jfa1daTTJWLUR6QWJrNU1FSEJ0U2lWdE02Q1BCcC1mdHQyMTZNTlB1U0xUaHpuQzNSWHBDckNoMUpoV1BNWV9tTUluUUYybTRRaWhMX1Z1VTE1ZzZUN3dlUDdNWE5LZjFNQzM3cEg5MC1Zak1QdEhheHE0Ynp1Y3U5eDd6N2E4TWZkMkxlRFlxU1Zhb3RmN0hrekdEU3FpT0FOV0VZejFONF9wZUtvaTJtTGZWTUhnRGJCZ2kxZHMwU1Vnbm9VM3FfdU9odkhfSGlFV3czWHNMQ19xUHIxYTRZYi1JSV94aDdSUEhlbUZTM3drZVVVbkItZU84VTlkdWIxQWliRDNtdHVySlQ2Z242dm9DblY5eWZ4cnM3d2pmd2VLNFctWnplSTlZdXowNWlUajVyS0QwZGdKM1BwdzVLUE44alhkWC00SzhMUUwybExqaEh4RHh5V3k0M2hzTVFUSmE2ajdPcDdqendhcVJhalJhOG96V1lwNmFlM281d0J5bkd5cHJrSXYwTDlRSWRjX0lQWHFmb3AwdU1NVjZKTkNGOW5xT21sVzJmZTd0dWQyY1cwUU9hRUstQk9NeXkyQi1Hbm1MSktVNmp1SExkbGQxN012ZjFyUklfbnBxNlBTbkRSX25XMTdtbVFaY3c1YkRrUTd1QW1zMXViTVhfY0dVNHM2SGRpMWF2WjVhNmFnajVCdzFxWXZvV1dka3lWaHd2U2tjcF80SU9felZpdHJVREVVckZ3SjFBRnd4czBzLWNYcUI0LVhJRzY1ZlpZenZSaXc2LTBOTFpfN05LMFZkSkJqb3BuVTBLcHRhUXlaRFJnQzhvMlc5Mnl5SmZXcnE1U3lKbWJONA==","email":"romanyrafaatt@gmail.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTZmY2E5MDIyLTVjZTAtNDc1My1iNWQ4LTNhNTJjYWMwZTIxNjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTRZekF5TmpWaVlXTXlNR1UwTW1SaE9USXpOakUxWW1VNE9HVm1Zemt6WkNKOS5SbENlZkVCWnpCdjZuSGtJYWpqd3ZYVEMyVTdVXzVEQVh4d1FRT0Jfa1daTTJWLUR6QWJrNU1FSEJ0U2lWdE02Q1BCcC1mdHQyMTZNTlB1U0xUaHpuQzNSWHBDckNoMUpoV1BNWV9tTUluUUYybTRRaWhMX1Z1VTE1ZzZUN3dlUDdNWE5LZjFNQzM3cEg5MC1Zak1QdEhheHE0Ynp1Y3U5eDd6N2E4TWZkMkxlRFlxU1Zhb3RmN0hrekdEU3FpT0FOV0VZejFONF9wZUtvaTJtTGZWTUhnRGJCZ2kxZHMwU1Vnbm9VM3FfdU9odkhfSGlFV3czWHNMQ19xUHIxYTRZYi1JSV94aDdSUEhlbUZTM3drZVVVbkItZU84VTlkdWIxQWliRDNtdHVySlQ2Z242dm9DblY5eWZ4cnM3d2pmd2VLNFctWnplSTlZdXowNWlUajVyS0QwZGdKM1BwdzVLUE44alhkWC00SzhMUUwybExqaEh4RHh5V3k0M2hzTVFUSmE2ajdPcDdqendhcVJhalJhOG96V1lwNmFlM281d0J5bkd5cHJrSXYwTDlRSWRjX0lQWHFmb3AwdU1NVjZKTkNGOW5xT21sVzJmZTd0dWQyY1cwUU9hRUstQk9NeXkyQi1Hbm1MSktVNmp1SExkbGQxN012ZjFyUklfbnBxNlBTbkRSX25XMTdtbVFaY3c1YkRrUTd1QW1zMXViTVhfY0dVNHM2SGRpMWF2WjVhNmFnajVCdzFxWXZvV1dka3lWaHd2U2tjcF80SU9felZpdHJVREVVckZ3SjFBRnd4czBzLWNYcUI0LVhJRzY1ZlpZenZSaXc2LTBOTFpfN05LMFZkSkJqb3BuVTBLcHRhUXlaRFJnQzhvMlc5Mnl5SmZXcnE1U3lKbWJONA==","email":"romanyrafaatt@gmail.com"}}}'

ssh_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAQRL1CIMFRlCigTjAIAM8iY0ndnKkCEgcILfsmo5+lU root@RHEL9-OCP'
rhsm_username: "room24"  
rhsm_password: "capvuw-gykhuD-6betsi" 

# WEB SERVER
httpd_root: "/var/www/html"
files_to_add:
  - "worker.ign"
  - "bootstrap.ign"
  - "master.ign"

nameserver: "8.8.8.8"  # Replace with your nameserver

# HAPROXY
haproxy_config: "/etc/haproxy/haproxy.cfg"
stats_desc: "Stats for ocp cluster"
haproxy_stats_user: "admin"
haproxy_stats_pass: "ocp"

# Create haproxy_servers dynamically
haproxy_servers: |
  api: 
    {% for vm in vms_info %}
      - { name: "{{ vm.hostname }}", host: "{{ vm.hostname }}.{{ OCP_CLUSTER_NAME }}.{{ OCP_BASE_DOMAIN }}", port: 6443, options: "{% if vm.hostname == 'bootstrap' %}check inter 1s backup{% else %}check inter 1s{% endif %}" }
    {% endfor %}

  mcs:
    {% for vm in vms_info %}
      - { name: "{{ vm.hostname }}", host: "{{ vm.hostname }}.{{ OCP_CLUSTER_NAME }}.{{ OCP_BASE_DOMAIN }}", port: 22623, options: "{% if vm.hostname == 'bootstrap' %}check inter 1s backup{% else %}check inter 1s{% endif %}" }
    {% endfor %}

  ingress:
    {% for vm in vms_info %}
      {% if vm.hostname != "bootstrap" %}
        - { name: "{{ vm.hostname }}", host: "{{ vm.hostname }}.{{ OCP_CLUSTER_NAME }}.{{ OCP_BASE_DOMAIN }}", port: 443, options: "check inter 1s" }
      {% endif %}
    {% endfor %}

    
