# ---
- name: Create a VM with custom resources
  hosts: localhost
  gather_facts: false
  vars_files:
    - vcenter_vars.yml
    # - vm_list.yml
  tasks:
    - name: Read the vm_list.yml file containing JSON data
      ansible.builtin.slurp:
        src: vm_list.yml
      register: vm_list_raw
    - name: Decode the base64 content and parse JSON
      set_fact:
        vm_list_json: "{{ vm_list_raw['content'] | b64decode | from_json }}"  
    - name: Debug vm_list
      debug:
        var: vm_list_json
    # - name: Create VMs dynamically
    #   community.vmware.vmware_guest:
    #     hostname: "{{ vcenter.hostname }}"
    #     username: "{{ vcenter.username }}"
    #     password: "{{ vcenter.password }}"
    #     validate_certs: "{{ validate_certs }}"
    #     datacenter: "{{ datacenter.name }}"
    #     cluster: "{{ datacenter.cluster }}"
    #     folder: "{{ item.folder }}"
    #     template: "{{ item.template }}"
    #     name: "{{ item.name }}"
    #     guest_id: "{{ item.guest_id }}"
    #     state: "{{ item.state}}"
    #     wait_for_ip_address: "{{ item.wait_for_ip_address }}"
    #     customization: "{{ item.customization}}"
    #     hardware:
    #       num_cpus: "{{ item.num_cpus }}"
    #       memory_mb: "{{ item.memory_mb }}"
    #     networks: "{{ item.networks }}"
    #     disk: "{{ item.disk}}"
    #   loop: "{{ vm_details }}"
    #   loop_control:
    #     label: "{{ item.name }}"
    #   register: vm
      
    - name: set a var using set_stats
      ansible.builtin.set_stats:
        data:
          vms: "{{ vm_list_raw }}"   

    

