# ---
# - name: Create a VM with custom resources
#   hosts: localhost
#   gather_facts: false
#   vars_files:
#     - vcenter_vars.yml
#     - vm_list.yml
#   tasks:
#     - name: Debug vm_list
#       debug:
#         var: vm_details
#       register: vm   
#     # - name: Create VMs dynamically
#     #   community.vmware.vmware_guest:
#     #     hostname: "{{ vcenter.hostname }}"
#     #     username: "{{ vcenter.username }}"
#     #     password: "{{ vcenter.password }}"
#     #     validate_certs: "{{ validate_certs }}"
#     #     datacenter: "{{ datacenter.name }}"
#     #     cluster: "{{ datacenter.cluster }}"
#     #     folder: "{{ item.folder }}"
#     #     template: "{{ item.template }}"
#     #     name: "{{ item.name }}"
#     #     guest_id: "{{ item.guest_id }}"
#     #     state: "{{ item.state}}"
#     #     wait_for_ip_address: "{{ item.wait_for_ip_address }}"
#     #     customization: "{{ item.customization}}"
#     #     hardware:
#     #       num_cpus: "{{ item.num_cpus }}"
#     #       memory_mb: "{{ item.memory_mb }}"
#     #     networks: "{{ item.networks }}"
#     #     disk: "{{ item.disk}}"
#     #   loop: "{{ vm_details }}"
#     #   loop_control:
#     #     label: "{{ item.name }}"
#     #   register: vm
      
#     - name: Save VM details to a JSON file
#       copy:
#         dest: /tmp/vm_details.json
#         content: "{{ vm | to_json }}" 
---
- name: First Playbook
  hosts: localhost
  tasks:
    - name: Set a shared variable
      set_fact:
        shared_variable: "Some value"
      delegate_to: localhost
    - name: Register another variable
      shell: "echo 'Another value'"
      register: result
      changed_when: false
      delegate_to: localhost

    - name: Ensure the directory exists
      file:
        path: "/var/lib/ansible"
        state: directory
        mode: '0755' 

    - name: Use template to save variables to a file
      template:
        src: "variables.yml.j2"  # Path to the template file
        dest: "/var/lib/ansible/variables.yml"  # Destination path on the local machine
        mode: '0644'
    


