---
- name: Set up OpenShift infrastructure
  hosts: 192.168.1.122
  become: yes
  vars_files:
    - configs.yml
  tasks:
    - name: Ensure httpd is installed and started
      yum:
        name: httpd
        state: latest

    - name: Start and enable httpd
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Copy ignition files to httpd root
      ansible.builtin.copy:
        src: "{{ OCP_INSTALL_DIR }}/{{ item }}"
        dest: "{{ httpd_root }}/"
        owner: apache
        group: apache
        mode: "0777"
        remote_src: true
      loop: "{{ files_to_add }}"

    - name: Check if nameserver is present in resolv.conf
      shell: grep -q "{{ nameserver }}" /etc/resolv.conf
      register: resolv_conf_check
      failed_when: resolv_conf_check.rc not in [0, 1]
      changed_when: resolv_conf_check.rc == 1

    - name: Add nameserver to resolv.conf if not present
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver {{ nameserver }}"
        state: present
      when: resolv_conf_check.rc == 1

    - name: Ensure haproxy is installed
      yum:
        name: haproxy
        state: latest

    - name: Create HAProxy configuration
      template:
        src: haproxy.cfg.j2
        dest: "{{ haproxy_config }}"
        owner: root
        group: root
        mode: "0644"

    - name: Start and enable haproxy
      systemd:
        name: haproxy
        state: started
        enabled: yes
        ignore_errors: yes

    - name: Ensure DHCP is installed
      yum:
        name: dhcp
        state: latest    

