- name: Automate OpenShift installation steps
  hosts: 192.168.1.122
  become: true
  gather_facts: false
  vars_files:
    - configs.yml
  tasks:
    - name: Read SSH key content
      slurp:
        src: /root/.ssh/id_ed25519.pub
      register: ssh_key
    # Step 1: Create install-config.yml
    - name: Create the install-config.yml file
      copy:
        dest: "{{ install_dir }}/install-config.yml"
        content: |
          apiVersion: v1
          baseDomain: "{{ base_domain }}"
          compute:
          - hyperthreading: Enabled
            name: worker
            replicas: "{{ compute_replicas }}"
          controlPlane:
            hyperthreading: Enabled
            name: master
            replicas: "{{ control_replicas }}"
          metadata:
            name: "{{ cluster_name }}"
          platform:
            none: {}
          fips: false
          pullSecret: "{{ pull_secret }}"
          sshKey: "{{ ssh_key.content }}"

    # Step 2: Run the `openshift-install create install-config` command
    - name: Run openshift-install to create install-config
      command: >
        openshift-install create install-config
      args:
        chdir: "{{ install_dir }}"

    # Step 3: Run the `openshift-install create manifests` command
    - name: Run openshift-install to create manifests
      command: >
        openshift-install create manifests
      args:
        chdir: "{{ install_dir }}"

    # Step 4: Check the mastersSchedulable parameter
    # - name: Check if mastersSchedulable is set to false
    #   command: grep "mastersSchedulable: false" "{{ install_dir }}/manifests/cluster-scheduler-02-config.yml"
    #   register: masters_schedulable_check
    #   failed_when: masters_schedulable_check.rc == 0
    #   changed_when: false

    - name: Display the mastersSchedulable check result
      debug:
        msg: "mastersSchedulable is correctly set to false."

    # Step 5: Run the `openshift-install create ignition-configs` command
    - name: Run openshift-install to create ignition-configs
      command: >
        openshift-install create ignition-configs
      args:
        chdir: "{{ install_dir }}"
