vm_details:
  # - name: "RHEL9-OCP"
  #   folder: "Romany"
  #   template: "rhel9_template"
  #   guest_id: "rhel9_64Guest"
  #   memory_mb: 16096
  #   num_cpus: 4
  #   state: poweredon
  #   wait_for_ip_address: true
  #   networks:
  #     - name: "VM Network"
  #       device_type: vmxnet3
  #       ip: "192.168.1.122"
  #       netmask: "255.255.255.0"
  #       gateway: "192.168.1.1"
  #       dns_servers:
  #       - 192.168.1.20
  #       - 8.8.8.8
  #   customization:
  #     autologon: true
  #     dns_servers:
  #     - 192.168.1.20
  #     - 8.8.8.8    
  #   disk:
  #     - size_gb: 80
  #       type: thin
  #       datastore: "datastore-14"
  #   cdrom:
  #     - controller_number: 0
  #       unit_number: 0
  #       controller_type: sata
  #       # iso_path: "[datastore1 (1)] ISO/rhel-9.5-x86_64-boot.iso"
  #       iso_path: "[datastore1 (1)] ISO/rhel-9.3-x86_64-dvd.iso"
  #       # iso_path: "[datastore-14] rhcos-4.16.3-x86_64-live.x86_64.iso"
  #       # iso_path: "[datastore1 (1)] ISO/rhel9.iso"
  #       state: present
  #       type: iso
        
  - name: "Bootstrap-Romany"
    folder: "Romany"
    template: "coreos_template"
    guest_id: "rhel9_64Guest"
    memory_mb: 16096
    num_cpus: 4
    state: poweredoff
    wait_for_ip_address: true
    networks:
      - name: "VM Network"
        device_type: vmxnet3
        type: dhcp
        start_connected: true
    customization:
      autologon: true
      dns_servers:
      - 192.168.1.20
      - 8.8.8.8       
    disk:
      - size_gb: 80
        type: thin
        datastore: "datastore-14"   
        
  # - name: "Worker1-Romany"
  #   folder: "Romany"
  #   template: "coreos_template"
  #   guest_id: "rhel9_64Guest"
  #   memory_mb: 16096
  #   num_cpus: 4
  #   state: poweredoff
  #   wait_for_ip_address: false
  #   networks:
  #     - name: "VM Network"
  #       device_type: vmxnet3
  #       type: dhcp
  #       start_connected: true
  #   customization:
  #     autologon: true
  #     dns_servers:
  #     - 192.168.1.20
  #     - 8.8.8.8       
  #   disk:
  #     - size_gb: 80
  #       type: thin
  #       datastore: "datastore-14" 

  # - name: "Master1-Romany"
  #   folder: "Romany"
  #   template: "coreos_template"
  #   guest_id: "rhel9_64Guest"
  #   memory_mb: 16096
  #   num_cpus: 4
  #   state: poweredoff
  #   wait_for_ip_address: false
  #   networks:
  #     - name: "VM Network"
  #       device_type: vmxnet3
  #       type: dhcp
  #       start_connected: true
  #   customization:
  #     autologon: true
  #     dns_servers:
  #     - 192.168.1.20
  #     - 8.8.8.8   
    disk:
      - size_gb: 80
        type: thin
        datastore: "datastore-14"      

