- name: Configure remote host
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check current hostname
      command: hostname
      register: current_hostname

    - name: Disable SELinux in configuration file
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
        state: present
        backrefs: yes

    - name: Stop and disable SELinux immediately (runtime)
      command: setenforce 0
      ignore_errors: true

    - name: Stop and disable firewalld service
      systemd:
        name: firewalld
        state: stopped
        enabled: no
