- name: Configure remote host
  hosts: all
  become: true
  gather_facts: false
  tasks:
    # Step 1: Disable SELinux
    - name: Disable SELinux in configuration file
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
        state: present
        backrefs: yes

    - name: Stop and disable SELinux immediately (runtime)
      command: setenforce 0
      ignore_errors: true

    # Step 2: Stop and disable firewalld
    - name: Stop and disable firewalld service
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    # Step 3: Generate SSH key
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: /root/.ssh/id_ed25519
        type: ed25519
        force: no
      register: ssh_key

    - name: Display generated SSH public key
      debug:
        msg: "Generated SSH public key: {{ ssh_key.public_key }}"

    # Step 4: Install HAProxy
    - name: Install HAProxy
      package:
        name: haproxy
        state: present

    - name: Install WebServer
      package:
        name: httpd
        state: present
    # Step 5: Download and install OpenShift Installer
    - name: Download OpenShift Installer
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
        dest: /tmp/openshift-install-linux.tar.gz

    - name: Extract OpenShift Installer to /usr/local/bin
      unarchive:
        src: /tmp/openshift-install-linux.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
      mode: '0755'

    - name: Verify OpenShift Installer installation
      command: openshift-install version
      register: openshift_installer_version
      ignore_errors: yes

    - name: Show OpenShift Installer version
      debug:
        msg: "OpenShift Installer version: {{ openshift_installer_version.stdout }}"

    # Step 6: Download and install OpenShift Client (oc and kubectl)
    - name: Download OpenShift Client
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
        dest: /tmp/openshift-client-linux.tar.gz

    - name: Extract OpenShift Client binaries to /usr/local/bin
      unarchive:
        src: /tmp/openshift-client-linux.tar.gz
        dest: /tmp/openshift-client/
        remote_src: yes
      mode: '0755'

    - name: Move oc and kubectl to /usr/local/bin
      command: mv /tmp/openshift-client/{oc,kubectl} /usr/local/bin/
      args:
        removes: /tmp/openshift-client/

    - name: Verify OpenShift Client installation
      command: oc version
      register: openshift_client_version
      ignore_errors: yes

    - name: Show OpenShift Client version
      debug:
        msg: "OpenShift Client version: {{ openshift_client_version.stdout }}"

    # Step 7: Create OCP install directory
    - name: Create OCP install directory
      file:
        path: /root/ocp-install
        state: directory
        mode: '0755'
