- name: Configure remote host
  hosts: all
  become: true
  gather_facts: false
  vars:
    ssh_key_path: "/root/.ssh/id_ed25519"
    ocp_install_dir: "/root/ocp-install"
    rhsm_username: "room24"  
    rhsm_password: "capvuw-gykhuD-6betsi" 
  tasks:
    # Step 0: Register with Red Hat Subscription Manager
    - name: Register with Red Hat Subscription Manager
      command: >
        subscription-manager register
        --username="{{ rhsm_username }}"
        --password="{{ rhsm_password }}"
      register: subscription_register

    - name: Verify subscription registration
      debug:
        msg: "Subscription registration result: {{ subscription_register.stdout }}"

    - name: Attach subscription if registration succeeded
      command: subscription-manager attach --auto
      when: subscription_register.rc == 0

    # Step 1: Disable SELinux
    - name: Disable SELinux in configuration file
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
        state: present
        backrefs: yes

    - name: Stop and disable SELinux immediately (runtime)
      command: setenforce 0
      ignore_errors: true

    # Step 2: Stop and disable firewalld
    - name: Stop and disable firewalld service
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    # Step 3: Generate SSH key
    - name: Generate SSH key if not exists
      command: ssh-keygen -t ed25519 -f "{{ ssh_key_path }}" -N ""
      args:
        creates: "{{ ssh_key_path }}"

    # Step 4: Install HAProxy
    - name: Install HAProxy
      package:
        name: haproxy
        state: present

    - name: Install WebServer
      package:
        name: httpd
        state: present

    # Step 5: Download and install OpenShift Installer
    - name: Download OpenShift Installer
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
        dest: /tmp/openshift-install-linux.tar.gz

    - name: Extract OpenShift Installer
      command: tar -xvf /tmp/openshift-install-linux.tar.gz -C /usr/local/bin/
      args:
        creates: /usr/local/bin/openshift-install

    - name: Verify OpenShift Installer installation
      command: openshift-install version
      register: openshift_installer_version
      ignore_errors: yes

    - name: Show OpenShift Installer version
      debug:
        msg: "OpenShift Installer version: {{ openshift_installer_version.stdout }}"

    # Step 6: Download and install OpenShift Client (oc and kubectl)
    - name: Download OpenShift Client
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
        dest: /tmp/openshift-client-linux.tar.gz

    - name: Extract OpenShift Client binaries
      command: tar -xvf /tmp/openshift-client-linux.tar.gz -C /tmp/
      args:
        creates: /tmp/oc

    - name: Move oc and kubectl to /usr/local/bin
      command: mv /tmp/{oc,kubectl} /usr/local/bin/
      args:
        removes: /tmp/oc

    - name: Verify OpenShift Client installation
      command: oc version
      register: openshift_client_version
      ignore_errors: yes

    - name: Show OpenShift Client version
      debug:
        msg: "OpenShift Client version: {{ openshift_client_version.stdout }}"

    # Step 7: Create OCP install directory
    - name: Create OCP install directory
      file:
        path: "{{ ocp_install_dir }}"
        state: directory
        mode: '0755'
