
---
- name: Set Up DHCP & Haproxy
  hosts: 192.168.1.122
  gather_facts: true

  tasks:
    - name: content of set_stats
      debug:
        var: vms
        
    - name: Ensure DHCP is installed
      package:
        name: dhcp-server
        state: present

    - name: Extract VM details  name, mac, and IP address
      set_fact:
        dhcp_hosts: "{{ vms.results | json_query('[].{hostname: ansible_facts.hostname, mac_address: ansible_facts.eth0.macaddress, ipv4_address: ansible_facts.ansible_default_ipv4.address}') }}"


    - name: Generate DHCP configuration
      template:
        src: dhcp_config.j2
        dest: /etc/dhcp/dhcpd.conf
      vars:
        dhcp_hosts: "{{ dhcp_hosts }}"
        
    - name: Display the complete DHCP configuration
      command: cat /etc/dhcp/dhcpd.conf
      register: dhcp_config_content

    - name: Output the DHCP configuration
      debug:
        msg: "{{ dhcp_config_content.stdout }}"    
        
    # - name: Start and enable DHCP service
    #   systemd:
    #     name: dhcpd
    #     state: started
    #     enabled: yes

    # - name: Restart DHCP service to apply configuration
    #   systemd:
    #     name: dhcpd
    #     state: restarted    
