
---
- name: Set Up DHCP & Haproxy
  hosts: 192.168.1.122
  gather_facts: true

  tasks:
    - name: content of set_stats
      debug:
        var: vms
        
    - name: Ensure DHCP is installed
      yum:
        name: dhcp
        state: latest

    - name: Extract VM details  name, mac, and IP address
      set_fact:
        dhcp_hosts: >
         {{
          vms.results | map(attribute='ansible_facts') | map(
          'combine', 
          {
            'hostname': item.ansible_facts['hostname'],
            'mac_address': item.ansible_facts['eth0']['macaddress'] if 'eth0' in item.ansible_facts else 'unknown_mac',
            'ipv4_address': item.ansible_facts['ansible_default_ipv4']['address'] if item.ansible_facts['ansible_default_ipv4'] is defined else 'unknown_ip'
          }
         ) | list
         }}

    - name: Generate DHCP configuration
      template:
        src: dhcp_config.j2
        dest: /etc/dhcp/dhcpd.conf
      vars:
        dhcp_hosts: "{{ dhcp_hosts }}"
        
    - name: Display the complete DHCP configuration
      command: cat /etc/dhcp/dhcpd.conf
      register: dhcp_config_content

    - name: Output the DHCP configuration
      debug:
        msg: "{{ dhcp_config_content.stdout }}"    
        
    # - name: Start and enable DHCP service
    #   systemd:
    #     name: dhcpd
    #     state: started
    #     enabled: yes

    # - name: Restart DHCP service to apply configuration
    #   systemd:
    #     name: dhcpd
    #     state: restarted    
