---
- name: Configure OCP agent installer
  hosts: ocp_helpers
  become: yes
  vars:
    ocp_config:
      cluster_name: "agent"
      base_domain: "room.com"
      pull_secret: "{{ vault_pull_secret }}"
      ssh_key: "{{ vault_ssh_pubkey }}"
      rendezvous_ip: "192.168.1.100"
      masters:
        - { mac: "00:11:22:33:44:55", ip: "192.168.1.101" }
        - { mac: "AA:BB:CC:DD:EE:FF", ip: "192.168.1.102" }
        - { mac: "66:77:88:99:00:11", ip: "192.168.1.103" }
      workers:
        - { mac: "22:33:44:55:66:77", ip: "192.168.1.201" }
        - { mac: "88:99:00:11:22:33", ip: "192.168.1.202" }

  tasks:
    - name: Install dependencies
      dnf:
        name:
          - nmstate
          - git
          - jq
        state: present

    - name: Download OpenShift tools
      block:
        - name: Get latest stable version
          uri:
            url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/release.txt"
          register: ocp_release

        - name: Set version fact
          set_fact:
            ocp_version: "{{ (ocp_release.content | b64decode).split('\n') | select('match','^Version:') | first | regex_replace('^Version:\\s+(.*)$','\\1') }}"

        - name: Download installer
          get_url:
            url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-install-linux.tar.gz"
            dest: "/tmp/openshift-install.tar.gz"

        - name: Download oc client
          get_url:
            url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-client-linux.tar.gz"
            dest: "/tmp/oc-client.tar.gz"

    - name: Install binaries
      block:
        - name: Extract openshift-install
          unarchive:
            src: /tmp/openshift-install.tar.gz
            dest: /usr/local/bin
            remote_src: yes
            mode: 0755

        - name: Extract oc
          unarchive:
            src: /tmp/oc-client.tar.gz
            dest: /usr/local/bin
            remote_src: yes
            mode: 0755

    - name: Create working directory
      file:
        path: "~/ocp-agent"
        state: directory

    - name: Create install-config
      template:
        src: install-config.j2
        dest: "~/ocp-agent/install-config.yaml"

    - name: Create agent-config
      template:
        src: agent-config.j2
        dest: "~/ocp-agent/agent-config.yaml"

    - name: Generate ISO
      command: 
        cmd: openshift-install agent create image --dir ~/ocp-agent --log-level=debug
        chdir: ~/ocp-agent
