---
- name: Create helper VM for OCP agent installation
  hosts: localhost
  gather_facts: false
  var_files: 
    - vcenter_vars.yml
    - vm_list.yml
  tasks:
    - name: Debug vm_list
      debug:
        var: vm_details
    - name: Create VMs dynamically
      community.vmware.vmware_guest:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter.name }}"
        cluster: "{{ datacenter.cluster }}"
        folder: "{{ item.folder }}"
        template: "{{ item.template }}"
        name: "{{ item.name }}"
        guest_id: "{{ item.guest_id }}"
        state: "{{ item.state}}"
        wait_for_ip_address: "{{ item.wait_for_ip_address }}"
        customization: "{{ item.customization}}"
        hardware:
          num_cpus: "{{ item.num_cpus }}"
          memory_mb: "{{ item.memory_mb }}"
        networks: "{{ item.networks }}"
        disk: "{{ item.disk}}"
      loop: "{{ vm_details }}"
      loop_control:
        label: "{{ item.name }}"
      register: vm 

    - name: Wait for VM IP
    community.vmware.vmware_guest_info:
      validate_certs: no
      hostname: "{{ vcenter.hostname }}"
      username: "{{ vcenter.username }}"
      password: "{{ vcenter.password }}"
      vm_id: "{{ item.instance.hw_product_id }}"
    register: vm_info
    until: vm_info.instance.guest.ip_address is defined
    retries: 5
    delay: 30
    loop: "{{ vm.results }}"
    loop_control:
      label: "{{ item.instance.name }

    - name: Add helper to inventory
      add_host:
        name: "{{ vm_info.instance.guest.ip_address }}"
        groups: ocp_helpers
