---
- name: Create helper VM for OCP agent installation
  hosts: localhost
  gather_facts: false
  var_files: 
    - vcenter_vars.yml
    - helper.yml
  tasks:
    - name: Create helper VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter.name }}"
        cluster: "{{ datacenter.cluster }}"
        folder: "{{ helper.folder }}"
        template: "{{ helper.template }}"
        name: "{{ helper.name }}"
        guest_id: "{{ helper.guest_id }}"
        state: "{{ helper.state}}"
        wait_for_ip_address: "{{ helper.wait_for_ip_address }}"
        customization: "{{ helper.customization}}"
        hardware:
          num_cpus: "{{ helper.num_cpus }}"
          memory_mb: "{{ helper.memory_mb }}"
        networks: "{{ helper.networks }}"
        disk: "{{ helper.disk}}"
      register: vm 

    - name: Wait for VM IP
      community.vmware.vmware_guest_info:
        validate_certs: no
        hostname: "{{ vcenter.hostname }}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        vm_id: "{{ vm.instance.hw_product_id }}"
      register: vm_info
      until: vm_info.instance.guest.ip_address is defined
      retries: 5
      delay: 30

    - name: Add helper to inventory
      add_host:
        name: "{{ vm_info.instance.guest.ip_address }}"
        groups: ocp_helpers
