- name: Trigger Workflow on GitHub Commit
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        url: /trigger
        port: 8080
  rules:
    - name: Trigger build and deploy on GitHub commit
      condition: >
         "push" in  event.payload.events
      actions:
        - debug:
            msg: Event Trigger with a action

        - vars:
            repository_url: "{{ event.payload.event.repository.clone_url }}"
            branch_name: "{{ event.payload.event.ref | regex_replace('refs/heads/', '') }}"
            
        - run_job_template:
            template_name: "Build and Push Docker Image"
            extra_vars:
              repo_url: "{{ repository_url }}"
               
