- name: Build and Push Docker Image
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Clone GitHub repository using HTTPS with PAT
      git:
        repo: https://github.com/rom-ra/e-commerce-boot.git
        dest: /tmp/commerace
        clone: yes
        version: HEAD
          
    - name: Build and Push Docker image to registry
      community.docker.docker_image_push:
        build:
          path: /tmp/commerace
        name: docker.io/roomdocker20253/eda-repo/eda_img
        tag: latest
        push: yes
        source: build
