- name: Build and Push Docker Image
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yml
  tasks:
    - name: Clone GitHub repository
      git:
        repo: https://rom-ra:githubroom2024@github.com/rom-ra/e-commerce-boot.git
        dest: /tmp/commerace
        clone: yes

    - name: Build and Push Docker image to registry
      community.docker.docker_image:
        build:
          path: /tmp/commerace
        name: docker.io/roomdocker20253/eda-repo/eda_img
        tag: latest
        push: yes
        source: build
