---
- name: Build and Push Docker image from GitHub repo
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Clone the GitHub repository
      git:
        repo: https://github.com/rom-ra/e-commerce-boot.git
        dest: /tmp/commerace
        clone: yes
        version: HEAD

    - name: Build Docker image from cloned repo and push to Docker Hub
      community.docker.docker_image:
        build:
          path: /tmp/commerace/E-commerce-platform/commerace-webapp/microservices/payment_service  # Path to the Dockerfile
        name: docker.io/roomdocker20253/eda-repo/eda_img  # Image name on Docker Hub
        tag: latest  # Image tag
        push: yes  # Push the image after building it
        source: build  # Specify the source as 'build' to build the image
        api_version: "auto"
        tls: false
        validate_certs: false
