- name: Build and Push Docker Image
  hosts: localhost
  collections:
    - community.docker
  gather_facts: false
  tasks:
    - name: Clone GitHub repository
      git:
        repo: "{{ repo_url }}"
        dest: /tmp/microservice

    - name: Build and Push Docker image to registry
      docker_image:
        build:
          path: /tmp/microservice
        name: docker.io/roomdocker20253/eda-repo/eda_img
        tag: latest
        push: yes
        source: build
