- name: Build and Push Docker Image
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Clone GitHub repository
      git:
        repo: https://github.com/rom-ra/e-commerce-boot/tree/main/E-commerce-platform/commerace-webapp/microservices/payment_service
        dest: /tmp/microservice

    - name: Build and Push Docker image to registry
      community.docker.docker_image_tag:
        build:
          path: /tmp/microservice
        name: docker.io/roomdocker20253/eda-repo/eda_img
        tag: latest
        push: yes
        source: build
