---
- name: Create a VM with custom resources
  hosts: localhost
  gather_facts: false
  vars_files:
    - vcenter_vars.yml  # Include the external vars file
  tasks:
    - name: Fetch vCenter credentials
       set_fact:
         vcenter_credentials: "{{ lookup('credentials', 'vcenter_c') }}"
    - name: Create VM in VMware vCenter
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_credentials.host }}"  # Assuming 'host' is part of your vCenter credentials.
        username: "{{ vcenter_credentials.username }}"
        password: "{{ vcenter_credentials.password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter.name }}"
        cluster: "{{ datacenter.cluster }}"
        folder: "{{ datacenter.folder }}"
        name: "{{ vm.name }}"
        guest_id: "{{ vm.guest_id }}"
        hardware:
          memory_mb: "{{ vm.memory_mb }}"
          num_cpus: "{{ vm.num_cpus }}"
        networks:
          - name: "{{ vm.network.name }}"
        disk:
          size_gb: "{{ vm.disk_size_gb }}"
          type: "{{ vm.disk_type}}"
          datastore: "{{ datacenter.datastore }}"
        wait_for_ip_address: "{{ vm.wait_ip_address }}"
        state: "{{ vm.state }}"
