---
- name: Create a VM with custom resources
  hosts: localhost
  gather_facts: false
  vars_files:
    - vcenter_vars.yml  # Include the external vars file
  tasks:
    - name: Fetch vCenter credentials
       ansible.builtin.set_fact:
         vcenter_credentials: "{{ lookup('credentials', 'vcenter_c') }}"
    - name: Create VM in VMware vCenter
      community.vmware.vmware_guest:
        hostname: "{{ lookup('credentials', 'vCenter_Credential_Name').host }}"  # Directly lookup and access the host
        username: "{{ lookup('credentials', 'vCenter_Credential_Name').username }}"  # Directly lookup and access the username
        password: "{{ lookup('credentials', 'vCenter_Credential_Name').password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter.name }}"
        cluster: "{{ datacenter.cluster }}"
        folder: "{{ datacenter.folder }}"
        name: "{{ vm.name }}"
        guest_id: "{{ vm.guest_id }}"
        hardware:
          memory_mb: "{{ vm.memory_mb }}"
          num_cpus: "{{ vm.num_cpus }}"
        networks:
          - name: "{{ vm.network.name }}"
        disk:
          size_gb: "{{ vm.disk_size_gb }}"
          type: "{{ vm.disk_type}}"
          datastore: "{{ datacenter.datastore }}"
        wait_for_ip_address: "{{ vm.wait_ip_address }}"
        state: "{{ vm.state }}"
