---
- name: Execute dynamic tasks
  hosts: localhost
  gather_facts: false
  vars_files:
    - vcenter_vars.yml
    - vm_list.yml
    - dynamic_vcenter_tasks.yml
  tasks:
    - name: Execute defined dynamic tasks on VCenter
      include_tasks: "{{ item.module }}"
      vars:
        args: "{{ item.args }}"
        loop: "{{ item.loop }}"
      loop: "{{ dynamic_vcenter_tasks }}"
      loop_control:
        label: "{{ item.name }}"
      register: echo 
