vm_details:
  - name: "MadeByAnsible"
    folder: "Romany"
    template: "rhel9_template"
    guest_id: "rhel8_64Guest"
    memory_mb: 4096
    num_cpus: 2
    state: poweredon
    wait_for_ip_address: true
    networks:
      - name: "VM Network"
        device_type: vmxnet3
        ip: "192.168.1.115"
        netmask: "255.255.255.0"
        gateway: "192.168.1.1"
        dns_servers:
            - "192.168.1.20"
            - "8.8.8.8"
    disk:
      - size_gb: 20
        type: thin
        datastore: "datastore-14"
    cdrom:
      - controller_number: 0
        unit_number: 0
        controller_type: sata
        iso_path: "[datastore1 (1)] ISO/rhel-8.6-x86_64-dvd.iso"
        state: present
        type: iso    

