vm_list: |
      {% for vm in vm_details %}
      - name: "{{ vm.name }}"
        folder: "{{vm.folder}}"
        guest_id: "{{ vm.guest_id}}"
        num_cpus: "{{ vm.num_cpus }}"
        memory_mb: "{{ vm.memory_mb }}"
        disks: "{{ vm.disks }}"
        state: "{{ vm.state}}"
        wait_for_ip_address: "{{ vm.wait_for_ip_address}}"
        cdrom: "{{vm.cdrom}}"
        networks: {{ vm.networks | to_nice_yaml(indent=4) }}
      {% endfor %}

vm_details:
  - name: "vm1"
    folder: "Romany"
    guest_id: "rhel9_64Guest"
    memory_mb: 4096
    num_cpus: 2
    state: poweredon
    wait_for_ip_address: true
    networks:
      - name: "VM Network"
        device_type: vmxnet3
        ip: "192.168.1.115"
        netmask: "255.255.255.0"
        gateway: "192.168.1.1"
        dns_servers:
            - "192.168.1.20"
            - "8.8.8.8"
    disks:
      - size_gb: 20
        type: thin
        datastore: "datastore-14"
    cdrom:
      - controller_number: 0
        unit_number: 0
        controller_type: sata
        iso_path: "[datastore1 (1)] ISO/rhel-9.3-x86_64-dvd.iso"
        state: present
        type: iso    

